"""
src/api/routers/forecast.py
============================
72-hour AQI forecast endpoints (Phase 6).

Endpoints
---------
GET /forecast/{station_id}
    Returns the most-recent 72-hour AQI + pollutant forecast for one station.
    If no trained model exists the response has model_trained=False and an
    informational message — it never returns HTTP 500.

GET /forecast/{station_id}/explain
    Returns the SHAP explanation for the most-recent forecast at one station.
    If SHAP is unavailable or models are not trained, returns a graceful
    empty explanation with shap_available=False.

Both endpoints read from the ``forecasts`` table written by the ingestion
pipeline's step 7 (and/or scripts/train_model.py).  They do NOT run model
inference on request — inference runs as part of the data pipeline.
"""

from __future__ import annotations

import json
from datetime import datetime, timedelta, timezone
from typing import Optional

from fastapi import APIRouter, HTTPException, Query

from src.api.dependencies import DbDep, StationsDep
from src.api.schemas import (
    ExplanationFeature,
    ForecastExplanationResponse,
    ForecastHour,
    ForecastResponse,
)
from src.utils.logger import get_logger

log = get_logger(__name__)
router = APIRouter(prefix="/forecast", tags=["Forecast"])

# How far back to search for an existing forecast generation
_FORECAST_LOOKBACK_HOURS = 72


def _station_exists(station_id: str, stations: list[dict]) -> bool:
    return any(s["station_id"] == station_id for s in stations)


@router.get(
    "/{station_id}",
    response_model=ForecastResponse,
    summary="72-hour AQI forecast for one station",
    description=(
        "Returns the most recent 72-hour AQI and pollutant forecast for a "
        "Delhi NCR monitoring station. "
        "Forecasts are generated by the AQI forecasting pipeline (XGBoost). "
        "If no forecast has been generated yet, returns an empty response "
        "with `model_trained=False` — never HTTP 500. "
        "Train the model first with `python scripts/train_model.py`."
    ),
)
def get_forecast(
    station_id: str,
    db: DbDep,
    stations: StationsDep,
    hours: int = Query(72, ge=1, le=72, description="Forecast horizon (max 72)"),
) -> ForecastResponse:
    """Return the most recent forecast rows for the given station."""
    if not _station_exists(station_id, stations):
        raise HTTPException(
            status_code=404,
            detail=f"Station '{station_id}' not found. Use GET /stations for valid IDs.",
        )

    # Look for forecasts generated within the last LOOKBACK hours
    gen_min = datetime.now(timezone.utc) - timedelta(hours=_FORECAST_LOOKBACK_HOURS)

    try:
        df = db.read_forecasts(
            station_id=station_id,
            generated_at_min=gen_min,
            limit=hours,
        )
    except Exception as exc:
        log.warning(f"[forecast] DB read failed for {station_id}: {exc}")
        df = None

    if df is None or df.empty:
        return ForecastResponse(
            station_id=station_id,
            model_trained=False,
            count=0,
            hourly=[],
            message=(
                "No forecast available. The model has not been trained yet, "
                "or the ingestion pipeline has not run since training. "
                "Run: python scripts/train_model.py"
            ),
        )

    # Keep only the most recent generation_at batch
    most_recent_gen = df["generated_at"].max()
    df = df[df["generated_at"] == most_recent_gen]
    # Apply horizon filter
    df = df[df["forecast_hour"] <= hours].sort_values("forecast_hour")

    hourly = [ForecastHour.from_db_row(row) for row in df.to_dict(orient="records")]

    generated_at_str = None
    if most_recent_gen is not None:
        generated_at_str = (
            most_recent_gen.isoformat()
            if hasattr(most_recent_gen, "isoformat")
            else str(most_recent_gen)
        )

    model_version = None
    if "model_version" in df.columns and df["model_version"].notna().any():
        model_version = str(df["model_version"].dropna().iloc[0])

    return ForecastResponse(
        station_id=station_id,
        generated_at=generated_at_str,
        model_version=model_version,
        model_trained=True,
        count=len(hourly),
        hourly=hourly,
    )


@router.get(
    "/{station_id}/explain",
    response_model=ForecastExplanationResponse,
    summary="SHAP explanation for the most recent forecast",
    description=(
        "Returns SHAP feature-importance explanations for the most recent "
        "72-hour forecast at one station. "
        "Explanations are pre-computed and stored in the forecasts table. "
        "If no explanation is available, returns `shap_available=False` "
        "with an informational message."
    ),
)
def get_forecast_explanation(
    station_id: str,
    db: DbDep,
    stations: StationsDep,
    target: str = Query(
        "pm25",
        description="Target pollutant to explain: pm25, pm10, o3, no2, aqi_computed",
    ),
) -> ForecastExplanationResponse:
    """Return pre-computed SHAP explanation for the most recent forecast."""
    if not _station_exists(station_id, stations):
        raise HTTPException(
            status_code=404,
            detail=f"Station '{station_id}' not found. Use GET /stations for valid IDs.",
        )

    valid_targets = {"pm25", "pm10", "o3", "no2", "aqi_computed"}
    if target not in valid_targets:
        raise HTTPException(
            status_code=422,
            detail=f"target must be one of {sorted(valid_targets)}.",
        )

    gen_min = datetime.now(timezone.utc) - timedelta(hours=_FORECAST_LOOKBACK_HOURS)

    try:
        df = db.read_forecasts(
            station_id=station_id,
            generated_at_min=gen_min,
            limit=72,
        )
    except Exception as exc:
        log.warning(f"[forecast/explain] DB read failed for {station_id}: {exc}")
        df = None

    no_data_response = ForecastExplanationResponse(
        station_id=station_id,
        target=target,
        horizon_hours=24,
        top_features=[],
        explanation_text="",
        inversion_detected=False,
        shap_available=False,
        message=(
            "No explanation available. Run the ingestion pipeline after "
            "training the model: python scripts/train_model.py"
        ),
    )

    if df is None or df.empty:
        return no_data_response

    # Use the most recent generation batch, first 24 hours
    most_recent_gen = df["generated_at"].max()
    df24 = df[(df["generated_at"] == most_recent_gen) & (df["forecast_hour"] <= 24)]

    if df24.empty or "top_features" not in df24.columns:
        return no_data_response

    # Read the stored top_features JSON from the first non-null row
    top_json = df24["top_features"].dropna()
    if top_json.empty:
        return no_data_response

    try:
        features_raw = json.loads(top_json.iloc[0])
    except (json.JSONDecodeError, TypeError):
        return no_data_response

    top_features = [
        ExplanationFeature(
            rank=f.get("rank", i + 1),
            name=f.get("name", ""),
            label=f.get("label", f.get("name", "")),
            shap_value=float(f.get("shap_value", 0.0)),
            contribution_pct=float(f.get("contribution_pct", 0.0)),
        )
        for i, f in enumerate(features_raw)
        if isinstance(f, dict)
    ]

    explanation_text = ""
    if "explanation_text" in df24.columns:
        texts = df24["explanation_text"].dropna()
        if not texts.empty:
            explanation_text = str(texts.iloc[0])

    inversion_detected = False
    if "inversion_detected" in df24.columns:
        vals = df24["inversion_detected"].dropna()
        if not vals.empty:
            inversion_detected = bool(vals.iloc[0])

    return ForecastExplanationResponse(
        station_id=station_id,
        target=target,
        horizon_hours=24,
        top_features=top_features,
        explanation_text=explanation_text,
        inversion_detected=inversion_detected,
        shap_available=True,
    )
